# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c3312125419475316bb5df41b79160e1ab63a6ca320b199e7e3a9d22d261e982babdc5e19a3024e2334cd47421ff09269509fa59d36f25134ab4e4e1dad37ff

test:
  secret_key_base: 81ea23d94313cfe6a056710bfa86d2adc52d21fd76eeb15f31f441337686378585ce8787cdbdef616d423bbaac3dfd40e6af3a7ff4a369963dede2431df32a5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
